_target_: topobenchmark.transforms.data_transform.DataTransform
transform_type: 'lifting'
transform_name: "SimplicialVietorisRipsLifting"
complex_dim: 3
preserve_edge_attr: False
signed: True
distance_threshold: 2.0
feature_lifting: ProjectionSum